
export const Posts = [
    {
        id:1,
        desc: "Love for all, hatered for None.",
        photo: "/image2/person/samanth.cms",
        date: "5 mins ago",
        userId:1,
        like:32,
        comment:10,
        },
        {
            id:2,
            desc: "Love for all, hatered for None.",
            photo:"/image2/person/sai1.jpg",
            date: "5 mins ago",
            userId:2,
            like:32,
            comment:10,
            }, 
         {
            id:3,
            desc: "Love for all, hatered for None.",
            photo: "/image2/person/tesla.jpg",
            date: "5 mins ago",
            userId:3,
            like:333,
            comment:133,
            },             
      {
     id:4,
     desc: "Love for all, hatered for None.",
      photo: "/image2/person/jeff bezozes.jpg",
    date: "5 mins ago",
   userId:4,
      like:32,
    comment:10,
  },
  {
    id:5,
    desc: "Love for all, hatered for None.",
     photo: "https://m.economictimes.com/thumb/msid-59337222,width-1200,height-900,resizemode-4,imgsize-157812/love-taking-pictures-heres-some-good-news-for-you.jpg",
   date: "5 mins ago",
  userId:5,
     like:32,
   comment:10,
 }, 
  {
    id:6,
    desc: "Love for all, hatered for None.",
     photo: "/image2/person/gril.jpg",
   date: "5 mins ago",
  userId:6,
     like:32,
   comment:10,
 }, 
  {
    id:7,
    desc: "Love for all, hatered for None.",
     photo: "/image2/person/ambani.jpg",
   date: "5 mins ago",
  userId:7,
     like:32,
   comment:10,
 },
   {
    id:8,
    desc: "Love for all, hatered for None.",
     photo: "/image2/person/apj.jpg",
   date: "5 mins ago",
  userId:8,
     like:32,
   comment:10,
 }, 
  {
    id:9,
    desc: "Love for all, hatered for None.",
     photo: "/image2/person/billgets.jpg",
   date: "5 mins ago",
  userId:9,
     like:32,
   comment:10,
 }, 
  {
    id:10,
    desc: "Love for all, hatered for None.",
     photo: "/image2/person/sai pallavi.jpg",
   date: "5 mins ago",
  userId:10,
     like:32,
   comment:10,
 }, 
 ]